# https://taskfile.dev

version: "3"

dotenv: [.env]
vars:
  VERSION:
    sh: cargo metadata --no-deps --format-version=1 | jq '.packages[0].version' -r
  IMAGE_TAG:
    sh: echo discrimy/sdgenbox:v{{ .VERSION }}
  

tasks:
  test:
    cmds:
      - cargo test
  watch-run:
    cmds:
      - cargo watch -x run
  lint:
    cmds:
      - cargo fmt
      - cargo clippy
  autofix:
    cmds:
      - cargo clippy --fix --allow-dirty
      - cargo fmt
  db-cli:
    cmds:
      - sqlite3 ${DATABASE_URL/sqlite:\/\//}
    interactive: true
  docker:build:
    cmds: ["docker build . -t {{ .IMAGE_TAG }}"]
  docker:publish:
    deps: ["docker:build"]
    cmds: ["docker push {{ .IMAGE_TAG }}"]
